


services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  mongo-populate:
    build:
      context: .
      dockerfile: ./mongo/Dockerfile
    volumes:
      - ./data_generation:/app/data_generation
      - ./mongo/_annotations.coco.json:/app/mongo/_annotations.coco.json
    depends_on:
      - mongodb

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - postgres-data:/var/lib/postgresql/data


  spark:
    build: spark_streaming
    container_name: spark
    ports:
      - "8080:8080"
      - "7077:7077"
    depends_on:
      - mosquitto

#  flask:
#    build:
#      context: ./flask-app
#    container_name: flask-app
#    ports:
#      - "5000:5000"
#    depends_on:
#      - postgres
#      - mongodb
#      - mosquitto


volumes:
  postgres-data:
    driver: local

#flask is for the moment commented out