version: '3.8'

networks:
  parking-net:
    driver: bridge

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - parking-net

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" 
    networks:
      - parking-net

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - parking-net

  spark:
    image: bitnami/spark:latest
    container_name: spark
    ports:
      - "8080:8080" 
      - "7077:7077"  
    depends_on:
      - mosquitto

  flask:
    build:
      context: ./flask-app
    container_name: flask-app
    ports:
      - "5000:5000"  
    depends_on:
      - postgres
      - mongodb
      - mosquitto
  networks:
      - parking-net

