

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log


  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  mongo-populate:
    build:
      context: .
      dockerfile: ./mongo/Dockerfile
    volumes:
      - ./data_generation:/app/data_generation
      - ./mongo/_annotations.coco.json:/app/mongo/_annotations.coco.json
    depends_on:
      - mongodb

  image-fetcher:
    build:
      context: .
      dockerfile: ./image_fetcher/Dockerfile
    volumes:
      - ./images:/app/images
    depends_on:
     - mongodb

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smart-parking
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  postgres-check:
    container_name: postgres-check
    build:
      context: ./postgres
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - mongodb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smart-parking


  spark:
    build: 
      context: ./spark_streaming
      dockerfile: Dockerfile
    container_name: spark
    ports:
      - "8080:8080"
      - "7077:7077"
    depends_on:
      - mosquitto
      - postgres
      - postgres-check

  data_processor:
    build:
      context: ./data_processor
      dockerfile: Dockerfile
    container_name: sarima
    volumes:
      - ./data_processor:/app/data_processor


  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    depends_on:
      - postgres
      - mosquitto
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smart-parking
    volumes:
      - ./consumer:/app

  flask:
    build:
      context: ./fragui
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - mongodb
      - mosquitto

